config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#show"

  namespace :author do
    resources :decks
    resources :quizzes
  end

  resources :answer_sheets, only: %i[create destroy show] do
    member do
      get "pause"
      get "resume"
    end
  end

  resources :answer_sheet_questions, only: %i[show update]

  namespace :dashboard do
    resources :users, only: %i[show update]
  end

  resources :users do
    member do
      patch "update_password", to: "users/passwords#update"
    end

    resources :study_plans, module: :users
  end

  resources :study_plans, only: [] do
    resources :quizzes, only: %i[create destroy], module: :study_plans
  end

  resources :decks, only: %i[index show] do
    resources :cards, shallow: true, module: :decks
  end

  resources :quizzes, only: %i[index show] do
    resources :questions, only: %i[create edit destroy new show update]
  end

  resources :questions, only: [] do
    resources :choices, only: %i[create destroy edit new update], module: :questions
  end

  resources :user_decks, only: %i[show create update] do
    resource :summary, only: %i[show], module: :user_decks
  end

  resources :user_deck_cards, only: %i[update]
end

app/views/shared/_back_button.html.erb
<%= link_to path, class: "inline-flex bg-primary text-white px-2 py-2 mb-4" do %>
  <%= render_icon "chevron_left" %>
  <%= t("buttons.back") %>
<% end %>

app/views/shared/_breadcrumbs.html.erb
<div class="mb-6">
  <ol class="flex px-2 text-sm border-t border-b border-gray-800">
    <% if breadcrumbs.any? %>
      <% breadcrumbs.each.with_index(1) do |breadcrumb, index| %>
        <li class="">
          <%= breadcrumb_item(breadcrumb, last_item: index == breadcrumbs.size) %>
        </li>
      <% end %>
    <% elsif Rails.env.development? %>
      <li class="py-2 italic text-gray-300">No breadcrumbs defined for this page.</li>
    <% end %>
  </ol>
</div>

app/views/shared/_confirmation_link.html.erb
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <div class="pt-2 my-4 text-center border-t border-gray-600">
    <%= link_to "Didn't receive confirmation instructions?", new_user_confirmation_path, class: "text-sm" %><br />
  </div>
<% end %>

app/views/shared/_devise_errors.html.erb
<% if defined?(resource) && resource&.errors.any? %>
  <%= render "shared/flash_wrapper", flash_type: "alert", use_time_out: false do %>
    <p>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </p>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.any? && flash.each do |flash_type, content| %>
  <% Array(content).each do |msg| %>
    <%= render "shared/flash_wrapper", flash_type: do %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_flash_wrapper.html.erb
<%# locals: (flash_type: "notice", use_time_out: true, time_out_delay: 3000) %>
<div
  class="absolute left-0 flex py-2 px-4 w-full mb-4 text-sm rounded top-0 <%= flash_class(flash_type) %>"
  data-turbo-cache="false"
  data-controller="flash"
  data-flash-use-time-out-value="<%= use_time_out %>"
  data-flash-time-out-delay-value="<%= time_out_delay %>"
  >
  <div class="flex flex-col justify-center">
    <%= yield %>
  </div>
  <button 
          type="button"
          class="flex ml-auto items-center justify-center rounded-full top-0 w-8 h-8 p-2 right-0 text-xl <%= flash_button_class(flash_type) %>"
          data-action="click->flash#onClick"
    >
    <span class="font-bold text-white">&times;</span>
  </button>
</div>

app/views/shared/_footer.html.erb
<footer class="p-4 text-center bg-white border-gray-200 dark:bg-gray-900">
  <p>&copy; <%= DateTime.now.year %> QuizIt</p>
</footer>

app/views/shared/_horizontal_or.html.erb
<div class="flex items-center my-2">
  <div class="flex-grow border-t border-gray-300"></div>
  <span class="mx-2 text-sm text-gray-500">OR</span>
  <div class="flex-grow border-t border-gray-300"></div>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-white border-b border-gray-700 dark:bg-gray-900" data-controller='navbar'>
  <div class="flex flex-wrap items-center justify-between max-w-screen-xl mx-auto">
    <a href="<%= root_path %>" class="flex items-center p-4 space-x-3 rtl:space-x-reverse">
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Quiz<span>IT</span></span>
    </a>
    <button
      data-navbar-target='button'
      data-collapse-toggle="navbar-default"
      type="button"
      data-action='click->navbar#onClick'
      class="inline-flex items-center justify-center w-10 h-10 p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
      aria-controls="navbar-default"
      aria-expanded="false"
      >
      <span class="sr-only">Open main menu</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default" data-navbar-target='linksContainer'>
      <ul class="flex flex-col mt-4 font-medium bg-gray-900 border border-gray-700 rounded-lg md:flex-row rtl:space-x-reverse md:mt-0 md:border-0">
        <li>
          <a href="<%= root_path %>" class="flex px-4 py-4 text-white hover:text-green-500" aria-current="page">Home</a>
        </li>
        <% if user_signed_in? %>
          <li class="relative group">
            <button class="flex items-center px-2 py-4">
              <span class="mr-1">Design</span>
              <%= render_icon "chevron_down", klass: "group-hover:-rotate-180 transition-transform ease-in-out duration-200 size-5" %>
            </button>
            <ul class="hidden mx-4 border border-gray-700 md:ml-4 group-hover:block md:absolute md:bg-gray-900 md:py-2 md:px-3 md:z-50 md:rounded md:top-12">
              <li>
                <%= link_to author_decks_path, class: "flex items-center py-2 px-2 text-gray-900 rounded hover:bg-gray-800 md:border-0 dark:text-white hover:text-green-500" do %>
                  <%= render_icon "flash", klass: "size-5 mr-1" %> Flashcards
                <% end %>
              </li>
              <li>
                <%= link_to author_quizzes_path, class: "flex items-center py-2 px-2 text-gray-900 rounded hover:bg-gray-800 md:border-0 dark:text-white hover:text-green-500" do %>
                  <%= render_icon "clipboard_doc", klass: "size-5 mr-1" %> Quizzes
                <% end %>
              </li>
            </ul>
          </li>
          <li class="relative group">
            <button class="flex items-center px-2 py-4">
              <span class="mr-1">Study</span>
              <%= render_icon "chevron_down", klass: "group-hover:-rotate-180 transition-transform ease-in-out duration-200 size-5" %>
            </button>
            <%# BEGIN Design sub-navigation %>
            <ul class="hidden mx-4 space-y-1 border border-gray-700 md:ml-4 group-hover:block md:absolute md:bg-gray-900 md:py-2 md:px-3 md:z-50 md:rounded md:top-12 min-w-44">
              <li>
                <%= link_to decks_path, class: "flex items-center py-2 px-2 text-gray-900 rounded hover:bg-gray-800 md:border-0 dark:text-white hover:text-green-500" do %>
                  <%= render_icon "flash", klass: "size-5 mr-1" %> Flashcards
                <% end %>
              </li>
              <li>
                <%= link_to quizzes_path, class: "flex items-center py-2 px-2 text-gray-900 rounded hover:bg-gray-800 md:border-0 dark:text-white hover:text-green-500" do %>
                  <%= render_icon "clipboard_doc", klass: "size-5 mr-1" %> Quizzes
                <% end %>
              </li>
              <li class="pt-1 border-t border-gray-700">
                <%= link_to user_study_plans_path(user_id: current_user), class: "flex items-center py-2 px-2 text-gray-900 rounded hover:bg-gray-800 md:border-0 dark:text-white hover:text-green-500" do %>
                  <%= render_icon "book_open", klass: "size-5 mr-1" %>Study Plans
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
        <li>
          <% if user_signed_in? %>
            <li class="flex items-center">
              <%= link_to dashboard_user_path( current_user ), class: "px-3 py-3" do %>
                <%= avatar(current_user) %>
              <% end %>
            </li>
            <%= link_to "Sign out",
                destroy_user_session_path,
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "block py-4 px-2 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 dark:text-white md:dark:hover:text-green-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          <% else %>
            <a
              href="<%= new_user_session_path %>"
              class="block px-2 py-4 text-white rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 hover:text-green-500"
            >
              Log In
            </a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_profile_bar.html.erb
<div class="bg-gray-800">
  <div class="flex max-w-screen-xl px-4 py-3 mx-auto bg-gray-800">
    <div class="flex items-center left-column">
      <%= link_to dashboard_user_path( current_user ), class: "flex items-center" do %>
        <%= avatar current_user %>
        <div class="ml-2">
          <p class="border-b border-gray-600"><%= current_user.username %></p>
          <p class="text-xs font-light text-gray-400 uppercase"><%= "padawan" %></p>
        </div>
      <% end %>
    </div>
    <div class="flex ml-auto right-column">
      <span class="vertical-separator bg-gray-900 h-100 w-[1px] mr-8"></span>
      <%= link_to "Continue your streak >", root_path, class: "flex items-center bg-green-700 border-b-4 border-green-600 rounded px-8 py-2" %>
    </div>
  </div>
</div>