config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#show"

  namespace :author do
    resources :decks
    resources :quizzes
  end

  resources :answer_sheets, only: %i[create destroy show] do
    member do
      get "pause"
      get "resume"
    end
  end

  resources :answer_sheet_questions, only: %i[show update]

  namespace :dashboard do
    resources :users, only: %i[show update]
  end

  resources :users do
    member do
      patch "update_password", to: "users/passwords#update"
    end

    resources :study_plans, module: :users
  end

  resources :study_plans, only: [] do
    resources :quizzes, only: %i[create destroy], module: :study_plans
  end

  resources :decks, only: %i[index show] do
    resources :cards, shallow: true, module: :decks
  end

  resources :quizzes, only: %i[index show] do
    resources :questions, only: %i[create edit destroy new show update]
  end

  resources :questions, only: [] do
    resources :choices, only: %i[create destroy edit new update], module: :questions
  end

  resources :user_decks, only: %i[show create update] do
    resource :summary, only: %i[show], module: :user_decks
  end

  resources :user_deck_cards, only: %i[update]
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :author, class_name: "User"

  has_many :cards, class_name: "Decks::Card"
  has_many :user_decks
  has_many :users, through: :user_decks

  validates :title, presence: true

  def time_to_complete
    avg_time_per_card = 10
    ActiveSupport::Duration.build(cards.count * avg_time_per_card).to_i
  end
end

app/models/deck/card.rb
class Deck::Card < ApplicationRecord
  self.table_name = "cards"

  belongs_to :deck

  validates :front, presence: true
  validates :back, presence: true
end

app/models/decks/card.rb
class Decks::Card < ApplicationRecord
  self.table_name = "cards"

  belongs_to :deck

  validates :front, presence: true
  validates :back, presence: true

  scope :new_cards, ->(user_deck) { where(deck_id: user_deck.deck_id).where.not(id: user_deck.user_deck_cards.select(:card_id)) }

  def self.model_name
    ActiveModel::Name.new(self, Decks)
  end
end

app/controllers/author/decks_controller.rb
class Author::DecksController < ApplicationController
  before_action :set_author
  before_action :set_deck, only: %i[destroy edit show update]
  before_action :set_breacrumbs, only: %i[edit index new show]

  def index
    @decks = policy_scope([ :author, Deck ])
  end

  def show
    authorize([ :author, @deck ])
  end

  def new
    @deck = authorize([ :author, @author.authored_decks.new ])
  end

  def create
    @deck = authorize([ :author, Deck.new(deck_params) ])
    if @deck.save
      flash[:notice] = t("flash.decks.create.success")
      redirect_to [ :author, @deck ]
    else
      flash.now[:alert] = t("flash.decks.create.error")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize([ :author, @deck ])
  end

  def update
    authorize([ :author, @deck ])
    if @deck.update(deck_params.except(:author_id))
      flash[:notice] = t("flash.decks.update.success")
      redirect_to [ :author, @deck ]
    else
      flash.now[:alert] = t("flash.decks.update.error")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize([ :author, @deck ])
    if @deck.destroy
      flash[:notice] = t("flash.decks.destroy.success")
      redirect_to author_decks_url
    else
      flash.now[:alert] = t("flash.decks.destroy.error")
      redirect_to author_decks_url
    end
  end

  private

    def deck_params
      params.require(:deck).permit(:title, :description, :author_id)
    end

    def set_author
      @author = current_user
    end

    def set_deck
      @deck = Deck.find(params[:id])
    end

    def set_breacrumbs
      add_breadcrumb("Design")
      add_breadcrumb("Flashcard Decks", author_decks_path)
      if @deck
        add_breadcrumb(@deck.title, author_deck_path(@deck))
      end
      if form_render?
        add_breadcrumb("#{params[:action].capitalize} Deck")
      end
    end
end

app/controllers/author/quizzes_controller.rb
module Author
  class QuizzesController < ApplicationController
    before_action :set_quiz, only: %i[destroy edit show update]
    before_action :set_author, only: %i[create destroy edit index new show]
    before_action :set_breadcrumbs
    before_action :authorize_access!, except: %i[create index new]

    def index
      # FIX: scope this to user => @author.quizzes
      @quizzes = policy_scope(Quiz, policy_scope_class: QuizPolicy::Scope)
    end

    def show
    end

    def new
      @quiz = authorize([ :author, @author.authored_quizzes.new ])
    end

    def create
      @quiz = authorize([ :author, @author.authored_quizzes.new(quiz_params) ])
      if @quiz.save
        flash[:notice] = t("flash.quizzes.create.success")
        redirect_to author_quiz_url(@quiz)
      else
        flash.now[:alert] = t("flash.quizzes.create.error")
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @quiz.update(quiz_params)
        flash[:notice] = t("flash.quizzes.update.success")
        redirect_to author_quiz_url(@quiz)
      else
        @author = @quiz.author
        flash[:alert] = t("flash.quizzes.update.error")
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @quiz.destroy
        flash[:notice] = t("flash.quizzes.destroy.success")
        redirect_to author_quizzes_url
      else
        flash[:alert] = t("flash.quizzes.destroy.error")
        redirect_to author_quizzes_url
      end
    end

    private

    def authorize_access!
      authorize([ :author, @quiz ])
    end

    def record_not_found_redirect_url
      author_quizzes_url
    end

    def unauthorized_redirect_url
      author_quizzes_url
    end

    def quiz_params
      params.require(:quiz).permit(:title, :description, :author_id)
    end

    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    def set_author
      @author = current_user
    end

    def set_breadcrumbs
      add_breadcrumb("Design")
      add_breadcrumb("Quizzes", author_quizzes_path) if @author.present?
      add_breadcrumb(@quiz.title, author_quiz_path(@quiz)) if @quiz.present?
    end
  end
end

app/controllers/decks/cards_controller.rb
class Decks::CardsController < ApplicationController
  before_action :set_deck, only: %i[new create]
  before_action :set_card, only: %i[show edit update destroy]
  before_action :set_breadcrumbs, only: %i[new create]

  def show
    @card = authorize(@card)
  end

  def new
    @card = authorize(@deck.cards.new)
  end

  def create
    @card = authorize(@deck.cards.new(card_params))
    unless @card.save
      flash.now[:alert] = t("flash.cards.create.error")
      return render :new, status: :unprocessable_entity
    end

    flash[:notice] = t("flash.cards.create.success")
    handle_follow_up_action(@deck, params[:follow_up_action])
  end

  def edit
    @card = authorize(@card)
    @deck = @card.deck
    set_breadcrumbs
  end

  def update
    @card.assign_attributes(card_params)
    @card = authorize(@card)
    @deck = @card.deck

    set_breadcrumbs
    unless @card.save
      flash.now[:alert] = t("flash.cards.update.error")
      render :edit, status: :unprocessable_entity and return
    end

    flash[:notice] = t("flash.cards.update.success")
    handle_follow_up_action(@card.deck, params[:follow_up_action])
  end

  def destroy
    @card = authorize(@card)
    @deck = @card.deck
    unless @card.destroy
      flash.now[:alert] = t("flash.cards.destory.erro")
      render :edit, status: :unprocessable_entity and return
    end

    flash[:notice] = t("flash.cards.destroy.success")
    redirect_back_or_to new_deck_card_url(@deck)
  end

  private

    def card_params
      params.require(:card).permit(:front, :back, :deck_id)
    end

    def handle_follow_up_action(deck, follow_up_action)
      case follow_up_action
      when "new"
        redirect_to new_deck_card_url(deck_id: deck.id)
      when "show"
        redirect_to author_deck_url(deck)
      else
        redirect_to new_deck_card_url(deck_id: deck.id)
      end
    end

    def set_card
      @card = Decks::Card.find(params[:id])
    end

    def set_breadcrumbs
      add_breadcrumb("Design")
      add_breadcrumb("Decks", author_decks_path)

      if @deck
        add_breadcrumb(@deck.title, author_deck_path(@deck))
      end

      if form_render?
        add_breadcrumb("#{params[:action].capitalize} Card")
      end
    end

    def set_deck
      @deck = Deck.includes(:cards).find(params[:deck_id])
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: %i[show]
  before_action :set_breadcrumbs, only: %i[index show]
  def index
    @decks = policy_scope(Deck)
  end

  def show
    @deck = authorize(@deck)
  end

  private

    def set_breadcrumbs
      add_breadcrumb "Study"
      add_breadcrumb "Decks", decks_path
      if @deck.present?
        add_breadcrumb @deck.title, nil
      end
    end

    def set_deck
      @deck = Deck.find(params[:id])
    end
end

app/views/author/decks/_card.html.erb
<li data-search-filter-target="item" class="flex items-center gap-3 p-2 border border-white">
  <%= card.front %>
  <div class="inline-flex ml-auto text-xs border border-gray-400">
    <%= link_to edit_card_path(card), class: 'btn-warning px-2 py-2 text-black', aria: { label: "Edit card" } do %>
      <span aria-hidden="true">
        <%= render_icon "pencil", klass: "size-4" %>
      </span>
    <% end %>
    <%= link_to card_path(card),
      data: {
        turbo_confirm: t("buttons.cards.delete"),
        turbo_method: :delete
      },
      aria: { label: "Delete card" },
      class: 'bg-alert text-white px-2 py-2' do %>
      <%= render_icon "x_circle", klass: "size-4" %>
    <% end %>
  </div>
</li>

app/views/author/decks/_deck.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
  <th scope="row" class="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
    <%= deck.title %>
  </th>
  <td class="px-3 py-2">
    <%= deck.description %>
  </td>
  <td class="px-3 py-2 text-right">
    <div class="inline-flex border border-gray-400">
      <%= link_to author_deck_path(deck),
        title: "view",
        aria: { label: "View Deck" },
        class: "bg-primary text-white px-2 py-2" do %>
        <%= render_icon "magnifying_glass", klass: "size-5" %>
      <% end %>
      <%= link_to author_deck_path(deck),
        data: {
          turbo_confirm: "Are you sure you want to delete this Deck? This action is permanent!",
          turbo_method: :delete
        },
        title: "delete",
        aria: { label: "Delete Deck" },
        class: "flex items-center bg-alert text-white px-2 py-2" do %>
        <%= render_icon "x_circle", klass: "size-5" %>
      <% end %>
    </div>
  </td>
</tr>

app/views/author/decks/_form.html.erb
<%= render "shared/breadcrumbs" %>
<div class="w-full max-w-xl mx-auto mt-10">
  <div class="w-full max-w-xl mx-auto mt-10 border border-gray-500 rounded">
    <section>
      <h2 class="py-2 text-xl text-center uppercase border-b border-gray-500 font-xl">
        <%= deck.persisted? ? "Edit" : "Create" %> Deck
      </h2>
      <%= form_with model: [:author, deck], class: "px-2" do |ff| %>
        <%= ff.hidden_field :author_id, value: author.id %>
        <div class="mb-4 field">
          <%= ff.label :title, class: "text-white text-xs font-semibold uppercase mb-2" %>
          <%= ff.text_field :title, placeholder: "Enter a short, descriptive title for your deck", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:bg-white focus:outline-none focus:shadow-outline" %>
          <%= display_field_error(deck, :title) %>
        </div>
        <div class="mb-4 field">
          <%= ff.label :description, class: "text-white text-xs font-semibold uppercase mb-2" %>
          <%= ff.text_area :description, rows: 8, placeholder: "Provide a brief description of what this deck covers", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
          <%= display_field_error(deck, :description) %>
        </div>
        <div class="flex items-center mb-4 actions">
          <%= ff.submit class: "btn btn-success text-center w-full  text-white font-semibold uppercase py-2 px-4 rounded focus:outline-none focus:shadow-outline actions cursor-pointer" %>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/author/decks/edit.html.erb
<%= render 'form', deck: @deck, author: @author %>

app/views/author/decks/index.html.erb
<%= render "shared/breadcrumbs" %>
<section>
  <div class="flex items-center mb-4">
    <h2 class="text-2xl font-semibold">Your FlashCards</h2>
    <%= link_to new_author_deck_path, class: "flex btn rounded ml-auto hover:btn-success transition ease-in-out duration-500" do %>
      <%= render_icon "plus" %>
      <span class="ml-2">Create Deck</span>
    <% end %>
  </div>
  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 rtl:text-right dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-3 py-3">
            Title
          </th>
          <th scope="col" class="px-3 py-3">
            Description
          </th>
          <th scope="col" class="px-3 py-3 text-right">
            Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <% @decks.each do |deck| %>
          <%= render 'deck', author: @author, deck: %>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/author/decks/new.html.erb
<%= render 'form', deck: @deck, author: @author %>

app/views/author/decks/show.html.erb
<%= render "shared/breadcrumbs" %>
<div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2">
  <section class="inline-flex flex-col self-start w-full md:w-1/3 bg-gray-800 rounded pt-4 pb-2 px-2 min-h-[400px]">
    <%= link_to edit_author_deck_path(@deck), class: "flex btn-sm hover:bg-warning hover:text-black rounded items-center ml-auto mb-2" do %>
      <%= render_icon "pencil", klass: "size-5 mr-1" %> Edit
    <% end %>
    <div class="inline-flex items-center p-1 px-4 bg-blue-500">
      <h2 class="text-3xl font-semi-bold">
        <%= @deck.title %> <br>
      </h2>
    </div>
    <div class="my-2 ml-4 font-semibold">
      <p>AUTHOR:</p>
      <p class="ml-3 italic font-light"><%= @author.username %></p>
    </div>
    <div class="mb-2 ml-4 font-semibold">
      <p class="">DESCRIPTION:</p>
      <% if @deck.description.present? %>
        <p class="ml-3 italic font-light"><%= @deck.description %></p>
      <% else %>
        <div class="p-2 ml-3 italic text-gray-500">
          <p class="font-semibold">No description available.</p>
          <p class="mb-2 text-sm">
            Consider adding a description to provide more information for users. You can include details about the quiz format, difficulty, or expected knowledge level.
          </p>
          <p class="text-sm not-italic text-gray-400">
            You can add a description via the <span class="font-semibold text-white">Edit</span> button above.
          </p>
        </div>
      <% end %>
    </div>
    <div class="flex justify-between mt-auto space-x-4 border-t border-gray-500">
      <p class="flex-1 p-1 text-xl font-light text-center uppercase">
        <% minutes = seconds_to_minutes(@deck.time_to_complete) %>
        <span class="text-2xl">
          <%= format_as_two_digits(minutes) %>
        </span><br>
        <%= 'minute'.pluralize(minutes) %>
      </p>
      <p class="flex-1 p-1 text-xl font-light text-center uppercase border-l border-gray-500">
        <span class="text-2xl"><%= format_as_two_digits(@deck.cards.count) %></span><br>
        Flashcards
      </p>
    </div>
  </section>
  <section data-controller="search-filter" class="flex flex-col w-full px-2 py-4 bg-gray-800 rounded md:w-2/3">
    <%= link_to new_deck_card_path(deck_id: @deck.id), class: "flex btn rounded ml-auto hover:btn-success transition ease-in-out duration-500" do %>
      <%= render_icon "plus" %>
      <span class="ml-2">Add Flashcard</span>
    <% end %>
    <div class="flex flex-col items-center justify-between py-2 mb-2 border-b border-gray-500 md:inline-flex md:flex-row">
      <h2 class="mb-1 text-2xl md:mb-0">
        Flashcards
      </h2>
      <form class="w-full md:w-auto">
        <label for="search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
        <div class="relative">
          <div class="absolute inset-y-0 flex items-center pointer-events-none start-0 ps-3">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
            </svg>
          </div>
          <%= search_field_tag :search, nil,
              data: {
                  "search-filter-target": "input",
                  action: "input->search-filter#onInput"
              },
              autocomplete: 'on',
              class: "block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500",
              placeholder: "Search" %>
        </div>
      </form>
    </div>
    <div class="max-h-[650px] h-full">
      <p data-search-filter-target="emptyMessage" class="hidden w-full mb-2 text-xl italic text-center text-gray-500">No Cards found - try a different search.</p>
      <% if @deck.cards.exists? %>
        <ul id="cards_list" class="flex flex-col gap-1 pr-6 overflow-y-scroll">
          <%= render partial: "card", collection: @deck.cards %>
        </ul>
      <% else %>
        <div id="no-questions-instructions" class="flex flex-col w-full h-full pt-4 justify-self-center">
          <h3 class="w-full mb-2 text-xl italic text-center text-gray-500">No flashcards available</h3>
          <p class="items-center text-center text-gray-500 text-balance">
            You can add flashcards to your deck using <br>
            the <span class="italic font-semibold text-white">Add Flashcard</span> button above.</p>
        </div>
      <% end %>
    </div>
  </section>
</div>