config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#show"

  namespace :author do
    resources :decks
    resources :quizzes
  end

  resources :answer_sheets, only: %i[create destroy show] do
    member do
      get "pause"
      get "resume"
    end
  end

  resources :answer_sheet_questions, only: %i[show update]

  namespace :dashboard do
    resources :users, only: %i[show update]
  end

  resources :users do
    member do
      patch "update_password", to: "users/passwords#update"
    end

    resources :study_plans, module: :users
  end

  resources :study_plans, only: [] do
    resources :quizzes, only: %i[create destroy], module: :study_plans
  end

  resources :decks, only: %i[index show] do
    resources :cards, shallow: true, module: :decks
  end

  resources :quizzes, only: %i[index show] do
    resources :questions, only: %i[create edit destroy new show update]
  end

  resources :questions, only: [] do
    resources :choices, only: %i[create destroy edit new update], module: :questions
  end

  resources :user_decks, only: %i[show create update] do
    resource :summary, only: %i[show], module: :user_decks
  end

  resources :user_deck_cards, only: %i[update]
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :author, class_name: "User"

  has_many :cards, class_name: "Decks::Card"
  has_many :user_decks
  has_many :users, through: :user_decks

  validates :title, presence: true

  def time_to_complete
    avg_time_per_card = 10
    ActiveSupport::Duration.build(cards.count * avg_time_per_card).to_i
  end
end

app/models/deck/card.rb
class Deck::Card < ApplicationRecord
  self.table_name = "cards"

  belongs_to :deck

  validates :front, presence: true
  validates :back, presence: true
end

app/models/decks/card.rb
class Decks::Card < ApplicationRecord
  self.table_name = "cards"

  belongs_to :deck

  validates :front, presence: true
  validates :back, presence: true

  scope :new_cards, ->(user_deck) { where(deck_id: user_deck.deck_id).where.not(id: user_deck.user_deck_cards.select(:card_id)) }

  def self.model_name
    ActiveModel::Name.new(self, Decks)
  end
end

app/controllers/author/decks_controller.rb
class Author::DecksController < ApplicationController
  before_action :set_author
  before_action :set_deck, only: %i[destroy edit show update]
  before_action :set_breacrumbs, only: %i[edit index new show]

  def index
    @decks = policy_scope([ :author, Deck ])
  end

  def show
    authorize([ :author, @deck ])
  end

  def new
    @deck = authorize([ :author, @author.authored_decks.new ])
  end

  def create
    @deck = authorize([ :author, Deck.new(deck_params) ])
    if @deck.save
      flash[:notice] = t("flash.decks.create.success")
      redirect_to [ :author, @deck ]
    else
      flash.now[:alert] = t("flash.decks.create.error")
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize([ :author, @deck ])
  end

  def update
    authorize([ :author, @deck ])
    if @deck.update(deck_params.except(:author_id))
      flash[:notice] = t("flash.decks.update.success")
      redirect_to [ :author, @deck ]
    else
      flash.now[:alert] = t("flash.decks.update.error")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize([ :author, @deck ])
    if @deck.destroy
      flash[:notice] = t("flash.decks.destroy.success")
      redirect_to author_decks_url
    else
      flash.now[:alert] = t("flash.decks.destroy.error")
      redirect_to author_decks_url
    end
  end

  private

    def deck_params
      params.require(:deck).permit(:title, :description, :author_id)
    end

    def set_author
      @author = current_user
    end

    def set_deck
      @deck = Deck.find(params[:id])
    end

    def set_breacrumbs
      add_breadcrumb("Design")
      add_breadcrumb("Flashcard Decks", author_decks_path)
      if @deck
        add_breadcrumb(@deck.title, author_deck_path(@deck))
      end
      if form_render?
        add_breadcrumb("#{params[:action].capitalize} Deck")
      end
    end
end

app/controllers/decks/cards_controller.rb
class Decks::CardsController < ApplicationController
  before_action :set_deck, only: %i[new create]
  before_action :set_card, only: %i[show edit update destroy]
  before_action :set_breadcrumbs, only: %i[new create]

  def show
    @card = authorize(@card)
  end

  def new
    @card = authorize(@deck.cards.new)
  end

  def create
    @card = authorize(@deck.cards.new(card_params))
    unless @card.save
      flash.now[:alert] = t("flash.cards.create.error")
      return render :new, status: :unprocessable_entity
    end

    flash[:notice] = t("flash.cards.create.success")
    handle_follow_up_action(@deck, params[:follow_up_action])
  end

  def edit
    @card = authorize(@card)
    @deck = @card.deck
    set_breadcrumbs
  end

  def update
    @card.assign_attributes(card_params)
    @card = authorize(@card)
    @deck = @card.deck

    set_breadcrumbs
    unless @card.save
      flash.now[:alert] = t("flash.cards.update.error")
      render :edit, status: :unprocessable_entity and return
    end

    flash[:notice] = t("flash.cards.update.success")
    handle_follow_up_action(@card.deck, params[:follow_up_action])
  end

  def destroy
    @card = authorize(@card)
    @deck = @card.deck
    unless @card.destroy
      flash.now[:alert] = t("flash.cards.destory.erro")
      render :edit, status: :unprocessable_entity and return
    end

    flash[:notice] = t("flash.cards.destroy.success")
    redirect_back_or_to new_deck_card_url(@deck)
  end

  private

    def card_params
      params.require(:card).permit(:front, :back, :deck_id)
    end

    def handle_follow_up_action(deck, follow_up_action)
      case follow_up_action
      when "new"
        redirect_to new_deck_card_url(deck_id: deck.id)
      when "show"
        redirect_to author_deck_url(deck)
      else
        redirect_to new_deck_card_url(deck_id: deck.id)
      end
    end

    def set_card
      @card = Decks::Card.find(params[:id])
    end

    def set_breadcrumbs
      add_breadcrumb("Design")
      add_breadcrumb("Decks", author_decks_path)

      if @deck
        add_breadcrumb(@deck.title, author_deck_path(@deck))
      end

      if form_render?
        add_breadcrumb("#{params[:action].capitalize} Card")
      end
    end

    def set_deck
      @deck = Deck.includes(:cards).find(params[:deck_id])
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: %i[show]
  before_action :set_breadcrumbs, only: %i[index show]
  def index
    @decks = policy_scope(Deck)
  end

  def show
    @deck = authorize(@deck)
  end

  private

    def set_breadcrumbs
      add_breadcrumb "Study"
      add_breadcrumb "Decks", decks_path
      if @deck.present?
        add_breadcrumb @deck.title, nil
      end
    end

    def set_deck
      @deck = Deck.find(params[:id])
    end
end

app/views/decks/_deck.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
  <th scope="row" class="px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
    <%= deck.title %>
  </th>
  <td class="px-3 py-2">
    <%= deck.description %>
  </td>
  <td class="px-3 py-2 text-right">
    <div class="inline-flex border border-gray-400">
      <%= link_to deck_path(deck),
        title: "view",
        aria: { label: "View Deck" },
        class: "bg-primary text-white px-2 py-2" do %>
        <%= render_icon "magnifying_glass", klass: "size-5" %>
      <% end %>
    </div>
  </td>
</tr>

app/views/decks/index.html.erb
<%= render "shared/breadcrumbs" %>
<section>
  <div class="flex items-center mb-4">
    <h2 class="text-2xl font-semibold">Community FlashCard Decks</h2>
  </div>
  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 rtl:text-right dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-3 py-3">
            Title
          </th>
          <th scope="col" class="px-3 py-3">
            Description
          </th>
          <th scope="col" class="px-3 py-3 text-right">
            Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <% @decks.each do |deck| %>
          <%= render 'deck', deck: %>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/decks/show.html.erb
<%= render "shared/breadcrumbs" %>
<div class="flex flex-col space-y-2 md:space-y-2 w-full lg:w-1/2 max-w-[600px]">
  <section class="flex flex-col self-start w-full pt-2 bg-gray-800 rounded">
    <div class="inline-flex items-center p-1 px-4 mb-4 bg-blue-500">
      <h1 class="text-4xl font-semi-bold">
        <%= @deck.title %> <br>
      </h1>
    </div>
    <div class="mb-2 ml-4 font-semibold">
      <p class="uppercase">Author:</p>
      <p class="ml-3 italic font-light"><%= @deck.author.username %></p>
    </div>
    <div class="mb-12 ml-4 font-semibold">
      <p class="uppercase">Description:</p>
      <p class="ml-3 italic font-light"><%= @deck.description %></p>
    </div>
    <div class="flex justify-between space-x-4 border-t border-gray-500">
      <p id="quiz-duration" class="flex-1 p-1 text-xl font-light text-center uppercase">
        <% minutes = seconds_to_minutes(@deck.time_to_complete) %>
        <span class="text-2xl">
          <%= format_as_two_digits(minutes) %>
        </span><br>
        <%= 'minute'.pluralize(minutes) %>
      </p>
      <p id="quiz-question-count" class="flex-1 p-1 text-xl font-light text-center uppercase border-l border-gray-500">
        <span class="text-2xl">
          <%= format_as_two_digits(@deck.cards.count) %>
        </span><br>
        <%= 'cards'.pluralize(@deck.cards.count) %>
      </p>
    </div>
  </section>
  <div class="flex flex-col p-4 space-y-4 border border-gray-500 rounded md:flex-row md:space-y-0 md:space-x-4">
    <%= button_to user_decks_path,
                    params: { user_deck: { deck_id: @deck.id, user_id: current_user.id } },
                    class: "flex items-center justify-center btn btn-primary rounded" do %>
      <%= render_icon("play_circle", klass: "size-5 mr-1") %> Study
    <% end %>
    <%#= link_to "#", class: "flex items-center justify-center btn btn-success rounded" do %>
      <%#= render_icon("plus", klass: "size-5 mr-1") %>  <!-- Add to Study Plan -->
      <%# end %>
    </div>
  </div>